server:
  port: 8080
  
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/delivery?useTimezone=true&serverTimezone=UTC
    user: root
    password: root 
    
security:
  jwt:
    token:
      secret-key: 53cr53
      expire-length: 3600000
      
springdoc:
  pathsToMatch: 
  - /restaurante-delivery/**
  swagger-ui:
    use-root-path: true 